# Generated by Django 2.2.7 on 2019-11-18 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_auto_20191117_1857"),
    ]

    operations = [
        migrations.AlterModelOptions(name="post", options={"ordering": ("-created",)},),
    ]
