version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Brandon24
      POSTGRES_DB: postgres
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./social_app:/social_app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db